apiVersion: v1
kind: Secret
metadata:
  name: my-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/hin22001/argocd
  password: QjMzZzU0NCQ=
  username: aGluMjIwMDFAZ21haWwuY29t