---
# Source: argo-application/templates/apps-template-git.yaml
# All argo application will be defined by this template
---
# Source: argo-application/templates/apps-template-helm.yaml
---
---
# Source: argo-application/templates/apps-template-git.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kustomize-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy: 
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: argo-application/templates/apps-template-git.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sync-waves
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sync-waves
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy: 
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: argo-application/templates/apps-template-helm.yaml
# All argo application will be defined by this template
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy: 
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Source: argo-application/templates/apps-template-helm.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-hooks
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-hooks
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-hooks
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
  syncPolicy: 
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
