global:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    helmRepoURL: https://hin22001.github.io/helm/

apps:
  jenkins:
    install: true
    helm:
      version: 0.1.14
  ingress-controller:
    install: true
    helm:
      version: 0.1.0
  grafana:
    install: true
    helm:
      version: 0.1.3
  prometheus:
    install: true
    helm:
      version: 0.1.0
      
