global:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    helmRepoURL: https://hin22001.github.io/helm/

apps:
  helm-guestbook: 
    install: true
  helm-hooks:
    install: true
  kustomize-guestbook:
    install: true
  sync-waves:
    install: true
  jenkins:
    install: true
    helm:
      version: 0.1.4
      
