# All argo application will be defined by this template
{{- $spec := .Values.spec }}
{{- $global := .Values.global }}
{{- range $name, $app := .Values.apps }}
  {{- if and $app.install (not $app.helm) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ default $name $app.namespace }}
    server: {{ $spec.destination.server }}
  project: default
  source:
    path: {{ $name }}
    repoURL: {{ $spec.source.repoURL }}
    targetRevision: {{ $spec.source.targetRevision }}
  syncPolicy: {{ toYaml $global.syncPolicy | nindent 4 }}
  {{ end }}
---
{{- end -}}